version: '3'

services:
  postgres:
    image: postgres:17.0-alpine
    container_name: medium-blog-app-postgres-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}     
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_DB: ${DB_NAME}         
    ports:
      - "5432:5432"                      
    volumes:
      - pgdata:/var/lib/postgresql/data  

  redis:
    image: redis:7.4.1  
    container_name: medium-blog-app-redis-server
    ports:
      - "6379:6379"          
    volumes:
      - redis_data:/data     

volumes:
  pgdata:
    driver: local
  redis_data:
    driver: local
