CREATE TABLE user(
  id BIGSERIAL PRIMARY KEY,
  user_id VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  password_hash VARCHAr(512) DEFAULT NULL,
  email_verfied_at TIMESTAMP DEFAULT NULL,
  deactivated_at TIMESTAMP DEFAULT NULL,
  deleted_at  TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CUURENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CUURENT_TIMESTAMP,
);